config/routes.rb
Rails.application.routes.draw do
resources :users do
  get 'playlists', to: 'playlists#find',  as: 'find'
end
  resources :playlists do

        resources :songs
      end

  root 'users#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  belongs_to :user
  has_many :songs
  validates :name, presence: true, uniqueness:true

end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :playlist
  
end

app/models/user.rb
class User < ApplicationRecord
  has_many :playlist
  validates :name, presence: true, uniqueness:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_action :set_playlist, only: [:show, :edit, :update, :destroy]
  @@user_id = nil

  # GET /playlists
  # GET /playlists.json
  def index
    if  @@user_id.nil?
        @playlists = Playlist.all
     else
         @playlists = Playlist.where(user_id: @@user_id)
         @@user_id = nil
    end
  end


  def find
    @@user_id = params[:user_id]
    redirect_to playlists_path
  end


  # GET /playlists/1
  # GET /playlists/1.json
  def show
    @song = Song.new
  end

  # GET /playlists/new
  def new
    @playlist = Playlist.new
  end

  # GET /playlists/1/edit
  def edit
  end

  # POST /playlists
  # POST /playlists.json
  def create
    @playlist = Playlist.new(playlist_params)

    respond_to do |format|
      if @playlist.save
        format.html { redirect_to @playlist, notice: 'Playlist was successfully created.' }
        format.json { render :show, status: :created, location: @playlist }
      else
        format.html { render :new }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /playlists/1
  # PATCH/PUT /playlists/1.json
  def update
    respond_to do |format|
      if @playlist.update(playlist_params)
        format.html { redirect_to @playlist, notice: 'Playlist was successfully updated.' }
        format.json { render :show, status: :ok, location: @playlist }
      else
        format.html { render :edit }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /playlists/1
  # DELETE /playlists/1.json
  def destroy
    @playlist.destroy
    respond_to do |format|
      format.html { redirect_to playlists_url, notice: 'Playlist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_playlist
      @playlist = Playlist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def playlist_params
      params.require(:playlist).permit(:name, :user_id)
    end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController


  def index
    @song = Song.all
  end

  def edit
    @song      = Song.find(params[:id])
    @playlist  = Playlist.find(params[:playlist_id])
  end
  def create
     @song = Song.new(song_params)
     @song.playlist_id = params[:playlist_id]
     if @song.save
          redirect_to playlist_path(params[:playlist_id]), notice: 'La canción se ha creado con éxito!'
        else
          redirect_to playlist_path(params[:playlist_id]), notice: 'La canción no  ha sido creado !'
        end
  end


  def destroy
    @song = Song.find(params[:id])
    @song.destroy
    redirect_to playlist_path(params[:playlist_id]), notice: 'La canción se ha elimando!'
  end

  def update
    @song = Song.find(params[:id])
    if @song.update(song_params)
      redirect_to playlist_path(params[:playlist_id]), notice: 'La canción se ha actualizado!'
    else
      redirect_to playlist_path(params[:playlist_id]), notice: 'Problemas al actualizar!'
    end
  end




    private

      # Never trust parameters from the scary internet, only allow the white list through.
      def song_params
        params.require(:song).permit(:name, :artis)
      end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Musify</title>

    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="mb-5">
      <nav class="navbar fixed-top  navbar-expand-lg navbar-dark bg-dark color_bar "  style="border-bottom: 5px solid  #F0AB00;">
      <div>
        <a href="<%= users_path %>" class="navbar-brand">
        <%= image_tag "logo.png", class:'img-fluid', alt:'Logo' %>
        </a>
      </div>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <h1>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item mr-3"><a href="<%= users_path  %>"     class="nav-link text-white">User</a></li>
          <li class="nav-item mr-3"><a href="<%= playlist_songs_path("1") %>"     class="nav-link text-white">Song</a></li>
          <li class="nav-item mr-3"><a href="<%= playlists_path %>"     class="nav-link text-white">PlayList</a></li>
        </ul>
        </h1>
      </div>
    </nav>
    <div class="sticky m-5"><br><br><<br><br></div>
    <div class="ml-5">
      <%= yield %>
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4" crossorigin="anonymous"></script>

  </body>
</html>

app/views/playlists/_form.html.erb
<%= form_with(model: playlist, local: true) do |form| %>
  <% if playlist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(playlist.errors.count, "error") %> prohibited this playlist from being saved:</h2>

      <ul>
      <% playlist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :playlist_name %>
  </div>



  <div class="field  input-group-prepend">
    <%= form.label :user_id, class:"input-group-text"  %>
    <%= form.select  :user_id,User.pluck(:name,:id), id: :playlist_user_id %>

    <%= form.submit "Accion",class:"btn btn-primary" %>
  </div>
<% end %>

app/views/playlists/edit.html.erb
<h1>Editing Playlist</h1>

<%= render 'form', playlist: @playlist %>

<%= link_to 'Show', @playlist,class:"btn btn-primary" %>
<%= link_to 'Back', playlists_path,class:"btn btn-primary" %>

app/views/playlists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Playlists</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th>Cantidad de Canciones</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @playlists.each do |playlist| %>
      <tr>
        <td><%= playlist.name %></td>
        <td><%= playlist.user.name %></td>
        <td class="text-center"><%= playlist.songs.count %></td>
        <td><%= link_to 'Show', playlist,class:"btn btn-primary" %></td>
        <td><%= link_to 'Edit', edit_playlist_path(playlist),class:"btn btn-primary" %></td>
        <td><%= link_to 'Destroy', playlist, method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-primary" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Playlist', new_playlist_path,class:"btn btn-primary" %>

app/views/playlists/new.html.erb
<h1>New Playlist</h1>

<%= render 'form', playlist: @playlist %>

<%= link_to 'Back', playlists_path,class:"btn btn-primary" %>

app/views/playlists/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Nombre de la Lista:  <%= @playlist.name %> </h1>
<h3>Nombre del usuario: <%= @playlist.user.name %></h3>

<%= link_to 'Edit', edit_playlist_path(@playlist) ,class:"btn btn-primary" %> |
<%= link_to 'Back', playlists_path ,class:"btn btn-primary" %>




<hr>
<hr>
<hr>
<hr>

<h1> Ingreso de una Cancion  a la Lista </h1>

<%= form_with(model: [@playlist,@song], local: true) do |form| %>
<div class="field">
  <%= form.label :artist %>
  <%= form.text_field :artis, id: :song_artist %>
</div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :song_name %>

    <%= form.submit "Accion",class:"btn btn-primary" %>
  </div>
<% end %>

<hr>
<hr>
<hr>
<hr>
<h1> Lista de Canciones Ingresadas </h1>

<table>
  <thead>
    <tr>
      <td><strong>Nombre Canción</strong></td>
      <td><strong>Arista</strong></td>
      <td><strong>Opciones</strong></td>
  </tr>
  </thead>
  <tbody>
<% @playlist.songs.each do |songs| %>
      <tr>
      <td><%= songs.name %></td>
      <td><%= songs.artis %></td>
      <td>
        <!-- <%= link_to 'Show', playlist_song_path(@playlist,songs) %></td> -->
        <%= link_to 'Edit', edit_playlist_song_path(@playlist,songs),class:"btn btn-primary" %>
        <%= link_to 'Destroy', playlist_song_path(@playlist,songs), method: :delete, data: { confirm: 'Are you sure?' } ,class:"btn btn-primary"%>
      </td>
    </tr>
<% end %>
</ul>

app/views/songs/edit.html.erb
<h1> New Song <h1>

  <p id="notice"><%= notice %></p>



  <h1> Modificacion de una Cancion </h1>

  <%= form_with(model: [@playlist,@song], local: true) do |form| %>
  <div class="field">
    <%= form.label :artista %>
    <%= form.text_field :artis, id: :song_artist %>
  </div>

    <div class="field">
      <%= form.label :nombre %>
      <%= form.text_field :name, id: :song_name %>
    </div>

    <div class="actions">
      <%= form.submit "Accion",class:"btn btn-primary" %>
    </div>
  <% end %>

app/views/songs/index.html.erb
<p id="notice"><%= notice %></p>

<h1> Lista de Canciones Ingresadas </h1>


<table>
  <thead>
    <tr>
      <td><strong>Nombre Canción</strong></td>
      <td><strong>Arista</strong></td>
  </tr>
  </thead>
  <tbody>
<% @song.each  do |songs| %>
      <tr>
      <td><%= songs.name %></td>
      <td><%= songs.artis %></td>
    </tr>
<% end %>
</tbody>
</table>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email %>



    <%= form.submit "Ingreso", class:"btn btn-primary" %>
  </div>
<% end %>
<hr><br>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user,class:"btn btn-primary" %> 
<%= link_to 'Back', users_path,class:"btn btn-primary" %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Cantidad de PlayList</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td class="text-center"><%= link_to user.playlist.count, user_find_path(user) %></td>
        <td><%= link_to 'Show', user,class:"btn btn-primary" %></td>
        <td><%= link_to 'Edit', edit_user_path(user),class:"btn btn-primary" %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-primary" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path ,class:"btn btn-primary"%>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path ,class:"btn btn-primary"%>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user),class:"btn btn-primary" %> 
<%= link_to 'Back', users_path,class:"btn btn-primary" %>